name: printing hello
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: testing on normal runner
        
      run: |
          
          echo "installing----------------------------------------------"
          pip install awscli==1.18.217 > /dev/null
          echo "pip install completed-----------------------------------"
          aws --version
          echot "for aws path ------------------------------------------"
          which aws

      

  build2:
    runs-on: self-hosted
    steps:    
    - name: testing on self-hosted

      run: |

        echo "hello programmers"
